/*   Error and other messages specific to the EAGLE library.
/*

/*   Messages for the error status codes.
/*


/*
/*   Messages related to reading the name_PARTS.CSV file produced by the Eagle
/*   BOM.ULP.
/*
msg bom_bom_bad
  lan english -def
    Invalid BOM attribute of "%p1s" found for part %p2s.
msg bom_infile_bad
  lan english -def
    The input file is not of the correct format.  Use the latest version
    of the Eagle ULP PARTS_CSV to produce the input file.
msg bom_is_bad
  lan english -def
    Invalid IS attribute of "%p1s" found for part %p2s.
msg bom_nbom
  lan english -def
    %p1i unique BOM parts found.
msg bom_ncomponents
  lan english -def
    %p1i individual components read.
msg bom_outfile
  lan english -def
    Created: "%p1s"
msg bom_qty_bad
  lan english -def
    Invalid QTY attribute of "%p1s" found for part %p2s.
msg bom_subst_bad
  lan english -def
    Invalid SUBST attribute of "%p1s" found for part %p2s.
msg bom_valstat_bad
  lan english -def
    Invalid VALSTAT attribute of "%p1s" found for part %p2s.
